// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_loyalty_point/test/src/services/api/auth_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_loyalty_point/src/models/auth/data_request_forgot_password_model.dart'
    as _i9;
import 'package:flutter_loyalty_point/src/models/auth/data_request_login_model.dart'
    as _i8;
import 'package:flutter_loyalty_point/src/models/auth/data_request_register_model.dart'
    as _i7;
import 'package:flutter_loyalty_point/src/models/auth/response_forgot_password_model.dart'
    as _i4;
import 'package:flutter_loyalty_point/src/models/auth/response_login_model.dart'
    as _i3;
import 'package:flutter_loyalty_point/src/models/auth/response_register_model.dart'
    as _i2;
import 'package:flutter_loyalty_point/src/services/api/auth_api_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseRegisterModel_0 extends _i1.SmartFake
    implements _i2.ResponseRegisterModel {
  _FakeResponseRegisterModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseLoginModel_1 extends _i1.SmartFake
    implements _i3.ResponseLoginModel {
  _FakeResponseLoginModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseForgotPasswordModel_2 extends _i1.SmartFake
    implements _i4.ResponseForgotPasswordModel {
  _FakeResponseForgotPasswordModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthAPIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthAPIService extends _i1.Mock implements _i5.AuthAPIService {
  MockAuthAPIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ResponseRegisterModel> register(
          {required _i7.DataRequestRegisterModel? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {#data: data},
        ),
        returnValue: _i6.Future<_i2.ResponseRegisterModel>.value(
            _FakeResponseRegisterModel_0(
          this,
          Invocation.method(
            #register,
            [],
            {#data: data},
          ),
        )),
      ) as _i6.Future<_i2.ResponseRegisterModel>);
  @override
  _i6.Future<_i3.ResponseLoginModel> login(
          {required _i8.DataRequestLoginModel? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#data: data},
        ),
        returnValue:
            _i6.Future<_i3.ResponseLoginModel>.value(_FakeResponseLoginModel_1(
          this,
          Invocation.method(
            #login,
            [],
            {#data: data},
          ),
        )),
      ) as _i6.Future<_i3.ResponseLoginModel>);
  @override
  _i6.Future<_i4.ResponseForgotPasswordModel> forgotPassword(
          {required _i9.DataRequestForgotPasswordModel? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#data: data},
        ),
        returnValue: _i6.Future<_i4.ResponseForgotPasswordModel>.value(
            _FakeResponseForgotPasswordModel_2(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#data: data},
          ),
        )),
      ) as _i6.Future<_i4.ResponseForgotPasswordModel>);
}
