// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_loyalty_point/test/src/services/api/products_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_loyalty_point/src/models/product/response_get_product_list_model.dart'
    as _i2;
import 'package:flutter_loyalty_point/src/models/product/response_get_product_model.dart'
    as _i3;
import 'package:flutter_loyalty_point/src/services/api/products_api_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseGetProductListModel_0 extends _i1.SmartFake
    implements _i2.ResponseGetProductListModel {
  _FakeResponseGetProductListModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseGetProductModel_1 extends _i1.SmartFake
    implements _i3.ResponseGetProductModel {
  _FakeResponseGetProductModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsAPIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsAPIService extends _i1.Mock
    implements _i4.ProductsAPIService {
  MockProductsAPIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ResponseGetProductListModel> getProducts(
          {required String? path}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {#path: path},
        ),
        returnValue: _i5.Future<_i2.ResponseGetProductListModel>.value(
            _FakeResponseGetProductListModel_0(
          this,
          Invocation.method(
            #getProducts,
            [],
            {#path: path},
          ),
        )),
      ) as _i5.Future<_i2.ResponseGetProductListModel>);
  @override
  _i5.Future<_i3.ResponseGetProductModel> getProductById(
          {required String? productId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [],
          {#productId: productId},
        ),
        returnValue: _i5.Future<_i3.ResponseGetProductModel>.value(
            _FakeResponseGetProductModel_1(
          this,
          Invocation.method(
            #getProductById,
            [],
            {#productId: productId},
          ),
        )),
      ) as _i5.Future<_i3.ResponseGetProductModel>);
}
