// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_loyalty_point/test/src/services/api/transactions_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_loyalty_point/src/models/transaction/data_request_create_transaction.dart'
    as _i6;
import 'package:flutter_loyalty_point/src/models/transaction/response_create_transaction_model.dart'
    as _i3;
import 'package:flutter_loyalty_point/src/models/transaction/response_get_transaction_list.dart'
    as _i2;
import 'package:flutter_loyalty_point/src/services/api/transactions_api_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseGetTransactionListModel_0 extends _i1.SmartFake
    implements _i2.ResponseGetTransactionListModel {
  _FakeResponseGetTransactionListModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseCreateTransactionModel_1 extends _i1.SmartFake
    implements _i3.ResponseCreateTransactionModel {
  _FakeResponseCreateTransactionModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionsAPIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionsAPIService extends _i1.Mock
    implements _i4.TransactionsAPIService {
  MockTransactionsAPIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ResponseGetTransactionListModel>
      getTransactionHistoryListFromAPI() => (super.noSuchMethod(
            Invocation.method(
              #getTransactionHistoryListFromAPI,
              [],
            ),
            returnValue: _i5.Future<_i2.ResponseGetTransactionListModel>.value(
                _FakeResponseGetTransactionListModel_0(
              this,
              Invocation.method(
                #getTransactionHistoryListFromAPI,
                [],
              ),
            )),
          ) as _i5.Future<_i2.ResponseGetTransactionListModel>);
  @override
  _i5.Future<_i2.ResponseGetTransactionListModel>
      getReedemHistoryListFromAPI() => (super.noSuchMethod(
            Invocation.method(
              #getReedemHistoryListFromAPI,
              [],
            ),
            returnValue: _i5.Future<_i2.ResponseGetTransactionListModel>.value(
                _FakeResponseGetTransactionListModel_0(
              this,
              Invocation.method(
                #getReedemHistoryListFromAPI,
                [],
              ),
            )),
          ) as _i5.Future<_i2.ResponseGetTransactionListModel>);
  @override
  _i5.Future<_i3.ResponseCreateTransactionModel> createTransaction(
          {required _i6.DataRequestCreateTransaction? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [],
          {#data: data},
        ),
        returnValue: _i5.Future<_i3.ResponseCreateTransactionModel>.value(
            _FakeResponseCreateTransactionModel_1(
          this,
          Invocation.method(
            #createTransaction,
            [],
            {#data: data},
          ),
        )),
      ) as _i5.Future<_i3.ResponseCreateTransactionModel>);
}
